kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  hostPath:
    path:  /mnt/data
  capacity:
    storage: 100Mi 
  accessModes:
    - ReadWriteOnce
  # nfs:
  #   path: /export/volumes/mongodb
  #   server: nfs-01
  # persistentVolumeReclaimPolicy: Retain
  # volumeMode: Filesystem
