apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - name: 80-4200
      port: 80
      targetPort: 4200
  selector:
    app: frontend
  type: NodePort
