apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
        - image: phico/frontend:1.0
          imagePullPolicy: Always
          name: frontend
          ports:
          - name: frontend
            containerPort: 4200
