apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - name: 80-4200
      port: 80
      protocol: TCP
      targetPort: 4200
  selector:
    app: frontend
  type: NodePort
status:
  loadBalancer: {}
