apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: 4200
      nodePort: {{ .Values.service.nodePort }} # TODO: Make this conditional
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
