config:
  guestbook_name: "MyPopRock Festival 2.0"
  backend_uri: "http://backend.default.svc.cluster.local/guestbook"
replicaCount: 1
image:
  repository: phico/frontend
  tag: "2.0"
service:
  port: 80
  type: NodePort
  nodePort: 31000
ingress:
  host: frontend.lab.local