kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-pv
  labels:
    type: local # Should this be a variable?
spec:
  storageClassName: manual # Make this configurable with logic
  capacity:
    storage: 100Mi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path:  /mnt/data
